//@ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v3.19.1
// source: services.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleBidiStreamingCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "./google/protobuf/empty";
import { Value } from "./google/protobuf/struct";
import {
  AdminGlobalMessage,
  AdminMessage,
  AdminPusherToBackMessage,
  AdminRoomMessage,
  BackToPusherSpaceMessage,
  BanMessage,
  BatchToPusherRoomMessage,
  DispatchEventRequest,
  DispatchGlobalEventRequest,
  EditMapCommandMessage,
  EditMapCommandsArrayMessage,
  EditMapCommandWithKeyMessage,
  EventRequest,
  EventResponse,
  ExternalModuleMessage,
  MapStorageClearAfterUploadMessage,
  MapStorageDeleteMessage,
  PingMessage,
  PusherToBackMessage,
  PusherToBackRoomMessage,
  PusherToBackSpaceMessage,
  RefreshRoomPromptMessage,
  RoomsList,
  SaveVariableRequest,
  ServerToAdminClientMessage,
  ServerToClientMessage,
  UpdateMapToNewestWithKeyMessage,
  VariableRequest,
  WorldFullWarningToRoomMessage,
} from "./messages";

export const protobufPackage = "";

/** Service handled by the "back". Pusher servers connect to this service. */
export type RoomManagerService = typeof RoomManagerService;
export const RoomManagerService = {
  /** Holds a connection between one given client and the back */
  joinRoom: {
    path: "/RoomManager/joinRoom",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: PusherToBackMessage) => Buffer.from(PusherToBackMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PusherToBackMessage.decode(value),
    responseSerialize: (value: ServerToClientMessage) => Buffer.from(ServerToClientMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ServerToClientMessage.decode(value),
  },
  /** Bidirectional connection used to send to a pusher messages related to a given room and to subscribe/unsubscribe to zones */
  listenRoom: {
    path: "/RoomManager/listenRoom",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: PusherToBackRoomMessage) => Buffer.from(PusherToBackRoomMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PusherToBackRoomMessage.decode(value),
    responseSerialize: (value: BatchToPusherRoomMessage) =>
      Buffer.from(BatchToPusherRoomMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => BatchToPusherRoomMessage.decode(value),
  },
  adminRoom: {
    path: "/RoomManager/adminRoom",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: AdminPusherToBackMessage) => Buffer.from(AdminPusherToBackMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AdminPusherToBackMessage.decode(value),
    responseSerialize: (value: ServerToAdminClientMessage) =>
      Buffer.from(ServerToAdminClientMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ServerToAdminClientMessage.decode(value),
  },
  sendAdminMessage: {
    path: "/RoomManager/sendAdminMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AdminMessage) => Buffer.from(AdminMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AdminMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  sendGlobalAdminMessage: {
    path: "/RoomManager/sendGlobalAdminMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AdminGlobalMessage) => Buffer.from(AdminGlobalMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AdminGlobalMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  ban: {
    path: "/RoomManager/ban",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BanMessage) => Buffer.from(BanMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => BanMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  sendAdminMessageToRoom: {
    path: "/RoomManager/sendAdminMessageToRoom",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AdminRoomMessage) => Buffer.from(AdminRoomMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AdminRoomMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  sendWorldFullWarningToRoom: {
    path: "/RoomManager/sendWorldFullWarningToRoom",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: WorldFullWarningToRoomMessage) =>
      Buffer.from(WorldFullWarningToRoomMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => WorldFullWarningToRoomMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  sendRefreshRoomPrompt: {
    path: "/RoomManager/sendRefreshRoomPrompt",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RefreshRoomPromptMessage) => Buffer.from(RefreshRoomPromptMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RefreshRoomPromptMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  getRooms: {
    path: "/RoomManager/getRooms",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Empty.decode(value),
    responseSerialize: (value: RoomsList) => Buffer.from(RoomsList.encode(value).finish()),
    responseDeserialize: (value: Buffer) => RoomsList.decode(value),
  },
  ping: {
    path: "/RoomManager/ping",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PingMessage) => Buffer.from(PingMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PingMessage.decode(value),
    responseSerialize: (value: PingMessage) => Buffer.from(PingMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => PingMessage.decode(value),
  },
  readVariable: {
    path: "/RoomManager/readVariable",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: VariableRequest) => Buffer.from(VariableRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => VariableRequest.decode(value),
    responseSerialize: (value: any | undefined) => Buffer.from(Value.encode(Value.wrap(value)).finish()),
    responseDeserialize: (value: Buffer) => Value.unwrap(Value.decode(value)),
  },
  listenVariable: {
    path: "/RoomManager/listenVariable",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: VariableRequest) => Buffer.from(VariableRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => VariableRequest.decode(value),
    responseSerialize: (value: any | undefined) => Buffer.from(Value.encode(Value.wrap(value)).finish()),
    responseDeserialize: (value: Buffer) => Value.unwrap(Value.decode(value)),
  },
  saveVariable: {
    path: "/RoomManager/saveVariable",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SaveVariableRequest) => Buffer.from(SaveVariableRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SaveVariableRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Dispatch an event to all users in the room */
  dispatchEvent: {
    path: "/RoomManager/dispatchEvent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DispatchEventRequest) => Buffer.from(DispatchEventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DispatchEventRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Listen to events dispatched in the room */
  listenEvent: {
    path: "/RoomManager/listenEvent",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: EventRequest) => Buffer.from(EventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => EventRequest.decode(value),
    responseSerialize: (value: EventResponse) => Buffer.from(EventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => EventResponse.decode(value),
  },
  handleMapStorageUploadMapDetected: {
    path: "/RoomManager/handleMapStorageUploadMapDetected",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MapStorageClearAfterUploadMessage) =>
      Buffer.from(MapStorageClearAfterUploadMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => MapStorageClearAfterUploadMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  handleMapStorageDeleteMapDetected: {
    path: "/RoomManager/handleMapStorageDeleteMapDetected",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MapStorageDeleteMessage) => Buffer.from(MapStorageDeleteMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => MapStorageDeleteMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Dispatch a scripting API message to ALL rooms */
  dispatchGlobalEvent: {
    path: "/RoomManager/dispatchGlobalEvent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DispatchGlobalEventRequest) =>
      Buffer.from(DispatchGlobalEventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DispatchGlobalEventRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Dispatch an externam module message to room and user if is defined */
  dispatchExternalModuleMessage: {
    path: "/RoomManager/dispatchExternalModuleMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ExternalModuleMessage) => Buffer.from(ExternalModuleMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ExternalModuleMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface RoomManagerServer extends UntypedServiceImplementation {
  /** Holds a connection between one given client and the back */
  joinRoom: handleBidiStreamingCall<PusherToBackMessage, ServerToClientMessage>;
  /** Bidirectional connection used to send to a pusher messages related to a given room and to subscribe/unsubscribe to zones */
  listenRoom: handleBidiStreamingCall<PusherToBackRoomMessage, BatchToPusherRoomMessage>;
  adminRoom: handleBidiStreamingCall<AdminPusherToBackMessage, ServerToAdminClientMessage>;
  sendAdminMessage: handleUnaryCall<AdminMessage, Empty>;
  sendGlobalAdminMessage: handleUnaryCall<AdminGlobalMessage, Empty>;
  ban: handleUnaryCall<BanMessage, Empty>;
  sendAdminMessageToRoom: handleUnaryCall<AdminRoomMessage, Empty>;
  sendWorldFullWarningToRoom: handleUnaryCall<WorldFullWarningToRoomMessage, Empty>;
  sendRefreshRoomPrompt: handleUnaryCall<RefreshRoomPromptMessage, Empty>;
  getRooms: handleUnaryCall<Empty, RoomsList>;
  ping: handleUnaryCall<PingMessage, PingMessage>;
  readVariable: handleUnaryCall<VariableRequest, any | undefined>;
  listenVariable: handleServerStreamingCall<VariableRequest, any | undefined>;
  saveVariable: handleUnaryCall<SaveVariableRequest, Empty>;
  /** Dispatch an event to all users in the room */
  dispatchEvent: handleUnaryCall<DispatchEventRequest, Empty>;
  /** Listen to events dispatched in the room */
  listenEvent: handleServerStreamingCall<EventRequest, EventResponse>;
  handleMapStorageUploadMapDetected: handleUnaryCall<MapStorageClearAfterUploadMessage, Empty>;
  handleMapStorageDeleteMapDetected: handleUnaryCall<MapStorageDeleteMessage, Empty>;
  /** Dispatch a scripting API message to ALL rooms */
  dispatchGlobalEvent: handleUnaryCall<DispatchGlobalEventRequest, Empty>;
  /** Dispatch an externam module message to room and user if is defined */
  dispatchExternalModuleMessage: handleUnaryCall<ExternalModuleMessage, Empty>;
}

export interface RoomManagerClient extends Client {
  /** Holds a connection between one given client and the back */
  joinRoom(): ClientDuplexStream<PusherToBackMessage, ServerToClientMessage>;
  joinRoom(options: Partial<CallOptions>): ClientDuplexStream<PusherToBackMessage, ServerToClientMessage>;
  joinRoom(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<PusherToBackMessage, ServerToClientMessage>;
  /** Bidirectional connection used to send to a pusher messages related to a given room and to subscribe/unsubscribe to zones */
  listenRoom(): ClientDuplexStream<PusherToBackRoomMessage, BatchToPusherRoomMessage>;
  listenRoom(options: Partial<CallOptions>): ClientDuplexStream<PusherToBackRoomMessage, BatchToPusherRoomMessage>;
  listenRoom(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<PusherToBackRoomMessage, BatchToPusherRoomMessage>;
  adminRoom(): ClientDuplexStream<AdminPusherToBackMessage, ServerToAdminClientMessage>;
  adminRoom(options: Partial<CallOptions>): ClientDuplexStream<AdminPusherToBackMessage, ServerToAdminClientMessage>;
  adminRoom(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<AdminPusherToBackMessage, ServerToAdminClientMessage>;
  sendAdminMessage(
    request: AdminMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendAdminMessage(
    request: AdminMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendAdminMessage(
    request: AdminMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendGlobalAdminMessage(
    request: AdminGlobalMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendGlobalAdminMessage(
    request: AdminGlobalMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendGlobalAdminMessage(
    request: AdminGlobalMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  ban(request: BanMessage, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  ban(
    request: BanMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  ban(
    request: BanMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendAdminMessageToRoom(
    request: AdminRoomMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendAdminMessageToRoom(
    request: AdminRoomMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendAdminMessageToRoom(
    request: AdminRoomMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendWorldFullWarningToRoom(
    request: WorldFullWarningToRoomMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendWorldFullWarningToRoom(
    request: WorldFullWarningToRoomMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendWorldFullWarningToRoom(
    request: WorldFullWarningToRoomMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendRefreshRoomPrompt(
    request: RefreshRoomPromptMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendRefreshRoomPrompt(
    request: RefreshRoomPromptMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  sendRefreshRoomPrompt(
    request: RefreshRoomPromptMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  getRooms(request: Empty, callback: (error: ServiceError | null, response: RoomsList) => void): ClientUnaryCall;
  getRooms(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RoomsList) => void,
  ): ClientUnaryCall;
  getRooms(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RoomsList) => void,
  ): ClientUnaryCall;
  ping(request: PingMessage, callback: (error: ServiceError | null, response: PingMessage) => void): ClientUnaryCall;
  ping(
    request: PingMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PingMessage) => void,
  ): ClientUnaryCall;
  ping(
    request: PingMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PingMessage) => void,
  ): ClientUnaryCall;
  readVariable(
    request: VariableRequest,
    callback: (error: ServiceError | null, response: any | undefined) => void,
  ): ClientUnaryCall;
  readVariable(
    request: VariableRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: any | undefined) => void,
  ): ClientUnaryCall;
  readVariable(
    request: VariableRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: any | undefined) => void,
  ): ClientUnaryCall;
  listenVariable(request: VariableRequest, options?: Partial<CallOptions>): ClientReadableStream<any | undefined>;
  listenVariable(
    request: VariableRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<any | undefined>;
  saveVariable(
    request: SaveVariableRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  saveVariable(
    request: SaveVariableRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  saveVariable(
    request: SaveVariableRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Dispatch an event to all users in the room */
  dispatchEvent(
    request: DispatchEventRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  dispatchEvent(
    request: DispatchEventRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  dispatchEvent(
    request: DispatchEventRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Listen to events dispatched in the room */
  listenEvent(request: EventRequest, options?: Partial<CallOptions>): ClientReadableStream<EventResponse>;
  listenEvent(
    request: EventRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<EventResponse>;
  handleMapStorageUploadMapDetected(
    request: MapStorageClearAfterUploadMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  handleMapStorageUploadMapDetected(
    request: MapStorageClearAfterUploadMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  handleMapStorageUploadMapDetected(
    request: MapStorageClearAfterUploadMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  handleMapStorageDeleteMapDetected(
    request: MapStorageDeleteMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  handleMapStorageDeleteMapDetected(
    request: MapStorageDeleteMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  handleMapStorageDeleteMapDetected(
    request: MapStorageDeleteMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Dispatch a scripting API message to ALL rooms */
  dispatchGlobalEvent(
    request: DispatchGlobalEventRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  dispatchGlobalEvent(
    request: DispatchGlobalEventRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  dispatchGlobalEvent(
    request: DispatchGlobalEventRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Dispatch an externam module message to room and user if is defined */
  dispatchExternalModuleMessage(
    request: ExternalModuleMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  dispatchExternalModuleMessage(
    request: ExternalModuleMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  dispatchExternalModuleMessage(
    request: ExternalModuleMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const RoomManagerClient = makeGenericClientConstructor(RoomManagerService, "RoomManager") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): RoomManagerClient;
  service: typeof RoomManagerService;
  serviceName: string;
};

/** Service handled by the "back" about spaces. Pusher servers connect to this service. */
export type SpaceManagerService = typeof SpaceManagerService;
export const SpaceManagerService = {
  watchSpace: {
    path: "/SpaceManager/watchSpace",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: PusherToBackSpaceMessage) => Buffer.from(PusherToBackSpaceMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PusherToBackSpaceMessage.decode(value),
    responseSerialize: (value: BackToPusherSpaceMessage) =>
      Buffer.from(BackToPusherSpaceMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => BackToPusherSpaceMessage.decode(value),
  },
} as const;

export interface SpaceManagerServer extends UntypedServiceImplementation {
  watchSpace: handleBidiStreamingCall<PusherToBackSpaceMessage, BackToPusherSpaceMessage>;
}

export interface SpaceManagerClient extends Client {
  watchSpace(): ClientDuplexStream<PusherToBackSpaceMessage, BackToPusherSpaceMessage>;
  watchSpace(options: Partial<CallOptions>): ClientDuplexStream<PusherToBackSpaceMessage, BackToPusherSpaceMessage>;
  watchSpace(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<PusherToBackSpaceMessage, BackToPusherSpaceMessage>;
}

export const SpaceManagerClient = makeGenericClientConstructor(SpaceManagerService, "SpaceManager") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SpaceManagerClient;
  service: typeof SpaceManagerService;
  serviceName: string;
};

/** Service handled by the "map-storage". Back servers connect to this service. */
export type MapStorageService = typeof MapStorageService;
export const MapStorageService = {
  ping: {
    path: "/MapStorage/ping",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PingMessage) => Buffer.from(PingMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PingMessage.decode(value),
    responseSerialize: (value: PingMessage) => Buffer.from(PingMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => PingMessage.decode(value),
  },
  handleEditMapCommandWithKeyMessage: {
    path: "/MapStorage/handleEditMapCommandWithKeyMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EditMapCommandWithKeyMessage) =>
      Buffer.from(EditMapCommandWithKeyMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => EditMapCommandWithKeyMessage.decode(value),
    responseSerialize: (value: EditMapCommandMessage) => Buffer.from(EditMapCommandMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => EditMapCommandMessage.decode(value),
  },
  handleUpdateMapToNewestMessage: {
    path: "/MapStorage/handleUpdateMapToNewestMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateMapToNewestWithKeyMessage) =>
      Buffer.from(UpdateMapToNewestWithKeyMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UpdateMapToNewestWithKeyMessage.decode(value),
    responseSerialize: (value: EditMapCommandsArrayMessage) =>
      Buffer.from(EditMapCommandsArrayMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer) => EditMapCommandsArrayMessage.decode(value),
  },
  handleClearAfterUpload: {
    path: "/MapStorage/handleClearAfterUpload",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MapStorageClearAfterUploadMessage) =>
      Buffer.from(MapStorageClearAfterUploadMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => MapStorageClearAfterUploadMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface MapStorageServer extends UntypedServiceImplementation {
  ping: handleUnaryCall<PingMessage, PingMessage>;
  handleEditMapCommandWithKeyMessage: handleUnaryCall<EditMapCommandWithKeyMessage, EditMapCommandMessage>;
  handleUpdateMapToNewestMessage: handleUnaryCall<UpdateMapToNewestWithKeyMessage, EditMapCommandsArrayMessage>;
  handleClearAfterUpload: handleUnaryCall<MapStorageClearAfterUploadMessage, Empty>;
}

export interface MapStorageClient extends Client {
  ping(request: PingMessage, callback: (error: ServiceError | null, response: PingMessage) => void): ClientUnaryCall;
  ping(
    request: PingMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PingMessage) => void,
  ): ClientUnaryCall;
  ping(
    request: PingMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PingMessage) => void,
  ): ClientUnaryCall;
  handleEditMapCommandWithKeyMessage(
    request: EditMapCommandWithKeyMessage,
    callback: (error: ServiceError | null, response: EditMapCommandMessage) => void,
  ): ClientUnaryCall;
  handleEditMapCommandWithKeyMessage(
    request: EditMapCommandWithKeyMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: EditMapCommandMessage) => void,
  ): ClientUnaryCall;
  handleEditMapCommandWithKeyMessage(
    request: EditMapCommandWithKeyMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: EditMapCommandMessage) => void,
  ): ClientUnaryCall;
  handleUpdateMapToNewestMessage(
    request: UpdateMapToNewestWithKeyMessage,
    callback: (error: ServiceError | null, response: EditMapCommandsArrayMessage) => void,
  ): ClientUnaryCall;
  handleUpdateMapToNewestMessage(
    request: UpdateMapToNewestWithKeyMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: EditMapCommandsArrayMessage) => void,
  ): ClientUnaryCall;
  handleUpdateMapToNewestMessage(
    request: UpdateMapToNewestWithKeyMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: EditMapCommandsArrayMessage) => void,
  ): ClientUnaryCall;
  handleClearAfterUpload(
    request: MapStorageClearAfterUploadMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  handleClearAfterUpload(
    request: MapStorageClearAfterUploadMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  handleClearAfterUpload(
    request: MapStorageClearAfterUploadMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const MapStorageClient = makeGenericClientConstructor(MapStorageService, "MapStorage") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MapStorageClient;
  service: typeof MapStorageService;
  serviceName: string;
};
