// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import ar_SA from './ar-SA'
import ca_ES from './ca-ES'
import de_DE from './de-DE'
import dsb_DE from './dsb-DE'
import en_US from './en-US'
import es_ES from './es-ES'
import fr_FR from './fr-FR'
import hsb_DE from './hsb-DE'
import it_IT from './it-IT'
import ja_JP from './ja-JP'
import ko_KR from './ko-KR'
import nl_NL from './nl-NL'
import pt_BR from './pt-BR'
import th_TH from './th-TH'
import zh_CN from './zh-CN'

const localeTranslations = {
	'ar-SA': ar_SA,
	'ca-ES': ca_ES,
	'de-DE': de_DE,
	'dsb-DE': dsb_DE,
	'en-US': en_US,
	'es-ES': es_ES,
	'fr-FR': fr_FR,
	'hsb-DE': hsb_DE,
	'it-IT': it_IT,
	'ja-JP': ja_JP,
	'ko-KR': ko_KR,
	'nl-NL': nl_NL,
	'pt-BR': pt_BR,
	'th-TH': th_TH,
	'zh-CN': zh_CN,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
